version: '3'
services:
  web:
    build: 
      dockerfile: web.dockerfile
      context: .
    image: todo-web
    container_name: todo-web
    working_dir: /var/www
    ports:
      - 8080:8080
    volumes:
      - ./web:/var/www
    networks:
      - todo-network
  api:
    build:
      dockerfile: api.dockerfile
      context: .
    image: todo-api
    container_name: todo-api
    working_dir: /var/www
    ports:
      - 3000:3000
    volumes:
      - ./api:/var/www
    networks:
      - todo-network
    
  mongo:
    image: mongo:4.4.8-focal
    container_name: todo-mongo
    ports:
      - 27017:27017
    volumes:
      - './mongo/:/data/db'
    networks:
      - todo-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: todo
  mongo-test:
    image: mongo:4.4.8-focal
    container_name: todo-mongo-test
    ports:
      - 27018:27017
    volumes:
      - './mongo/test:/data/db'
    networks:
      - todo-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: todo_test
  # mongo-express:
  # mongo-express-test:
networks:
  todo-network:
    driver: bridge
